package http

import (
	"net/http"
	"os"
	"path/filepath"

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
	"vessl.dev/vessl/dashboard"
	_ "vessl.dev/vessl/docs"
)

func (s *Server) registerRoutes() {
	apiGroup := s.router.Group("/api")

	s.router.GET("/docs", func(c echo.Context) error {
		return c.Redirect(http.StatusMovedPermanently, "/docs/index.html")
	})
	s.router.GET("/docs/*", echoSwagger.WrapHandler)

	authGroup := apiGroup.Group("")
	authGroup.Use(s.authGuard.RequireAuth())
	apiGroup.POST("/auth/signup", s.authHandler.Register, s.authRateLimiter.Middleware)
	apiGroup.POST("/auth/signin", s.authHandler.Login, s.authRateLimiter.Middleware)
	apiGroup.POST("/auth/forgot-password", s.authHandler.ForgotPassword, s.authRateLimiter.Middleware)
	apiGroup.POST("/auth/reset-password", s.authHandler.ResetPassword, s.authRateLimiter.Middleware)
	apiGroup.GET("/system/public", s.settingsHandler.GetPublicSettings)
	apiGroup.GET("/system/setup-status", s.onboardingHandler.SetupStatus)
	apiGroup.POST("/system/setup", s.onboardingHandler.Setup)
	authGroup.GET("/system/stats", s.systemHandler.GetStats)
	apiGroup.POST("/system/restart", s.systemHandler.Restart, s.authGuard.RequireRole("admin"))
	apiGroup.POST("/system/maintenance/cleanup", s.systemHandler.Cleanup, s.authGuard.RequireRole("admin"))
	apiGroup.POST("/system/export", s.migrationHandler.Export, s.authGuard.RequireRole("admin"))
	apiGroup.POST("/system/import", s.migrationHandler.Import, s.authGuard.RequireRole("admin"))
	authGroup.POST("/compose/deploy", s.composeHandler.Deploy)
	authGroup.POST("/deploy/archive", s.archiveHandler.DeployArchive)
	authGroup.GET("/one-click", s.oneClickHandler.List)
	authGroup.POST("/one-click/deploy", s.oneClickHandler.Deploy)
	authGroup.GET("/auth/me", s.userHandler.GetProfile)
	apiGroup.POST("/auth/logout", s.authHandler.Logout)
	authGroup.GET("/users", s.userHandler.ListUsers, s.authGuard.RequireRole("admin"))
	authGroup.POST("/users/invite", s.authHandler.AdminInviteUser, s.authGuard.RequireRole("admin"))
	authGroup.DELETE("/users/:id", s.userHandler.DeleteUser, s.authGuard.RequireRole("admin"))
	authGroup.GET("/projects", s.projectHandler.ListProjects)
	authGroup.POST("/projects", s.projectHandler.CreateProject)
	authGroup.GET("/projects/:id", s.projectHandler.GetProject)
	authGroup.DELETE("/projects/:id", s.projectHandler.DeleteProject)
	authGroup.POST("/projects/:id/deploy", s.deploymentHandler.DeployProject, s.authGuard.RequireScope("deploy:write"))
	authGroup.GET("/projects/:id/domains", s.domainHandler.ListByProject)
	authGroup.POST("/projects/:id/domains", s.domainHandler.Create)
	authGroup.DELETE("/domains/:id", s.domainHandler.Delete)
	authGroup.POST("/dns", s.dnsHandler.Create)
	authGroup.GET("/dns", s.dnsHandler.List)
	authGroup.PUT("/dns/:id", s.dnsHandler.Update)
	authGroup.DELETE("/dns/:id", s.dnsHandler.Delete)
	authGroup.GET("/projects/:id/env", s.projectEnvHandler.GetVars, s.authGuard.RequireScope("env:read"))
	authGroup.PUT("/projects/:id/env", s.projectEnvHandler.SetVars, s.authGuard.RequireScope("env:write"))
	authGroup.GET("/databases", s.dbHandler.ListDatabases, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases", s.dbHandler.CreateDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.GET("/databases/:id", s.dbHandler.GetDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.PUT("/databases/:id", s.dbHandler.UpdateDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.DELETE("/databases/:id", s.dbHandler.DeleteDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/start", s.dbHandler.StartDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/stop", s.dbHandler.StopDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/restart", s.dbHandler.RestartDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/query", s.dbHandler.QueryDatabase, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/import", s.dbHandler.ImportData, s.authGuard.RequireScope("database:manage"))

	authGroup.GET("/databases/:id/schemas", s.dbHandler.GetSchemas, s.authGuard.RequireScope("database:manage"))
	authGroup.GET("/databases/:id/data/:table", s.dbHandler.GetTableData, s.authGuard.RequireScope("database:manage"))
	authGroup.POST("/databases/:id/data/:table", s.dbHandler.InsertTableRow, s.authGuard.RequireScope("database:manage"))
	authGroup.PUT("/databases/:id/data/:table", s.dbHandler.UpdateTableRow, s.authGuard.RequireScope("database:manage"))
	authGroup.DELETE("/databases/:id/data/:table", s.dbHandler.DeleteTableRow, s.authGuard.RequireScope("database:manage"))

	authGroup.GET("/jobs", s.jobHandler.ListProjectJobs)
	authGroup.POST("/jobs", s.jobHandler.Create)
	authGroup.GET("/jobs/:id", s.jobHandler.Get)
	authGroup.DELETE("/jobs/:id", s.jobHandler.Delete)
	authGroup.POST("/jobs/:id/trigger", s.jobHandler.Run)
	authGroup.POST("/git/connect", s.gitHandler.Connect)
	authGroup.GET("/git/status", s.gitHandler.Status)
	authGroup.DELETE("/git/connect/:provider", s.gitHandler.Disconnect)
	authGroup.GET("/git/repos", s.gitHandler.ListRepos)
	apiGroup.POST("/webhooks/git/:projectId", s.webhookHandler.HandleProjectWebhook)
	apiGroup.POST("/webhooks/git/services/:serviceId", s.webhookHandler.HandleServiceWebhook)
	apiGroup.POST("/webhooks/github/services/:serviceId", s.webhookHandler.HandleGitHubWebhook)
	authGroup.GET("/canvas/projects", s.canvasHandler.ListCanvasSummaries)
	authGroup.GET("/projects/:id/summary", s.canvasHandler.GetCanvasSummary)
	authGroup.GET("/environments/:id/canvas", s.canvasHandler.GetEnvironmentCanvas)
	authGroup.POST("/projects/:id/environments", s.environmentHandler.Create)
	authGroup.GET("/projects/:id/environments", s.environmentHandler.ListByProject)
	authGroup.DELETE("/environments/:id", s.environmentHandler.Delete)
	authGroup.POST("/environments/:id/apps", s.appServiceHandler.Create)
	authGroup.GET("/environments/:id/apps", s.appServiceHandler.ListByEnvironment)
	authGroup.GET("/projects/:id/apps", s.appServiceHandler.ListByProject)
	authGroup.GET("/apps/:id", s.appServiceHandler.Get)
	authGroup.PUT("/apps/:id", s.appServiceHandler.Update)
	authGroup.DELETE("/apps/:id", s.appServiceHandler.Delete)
	authGroup.POST("/apps/:id/stop", s.appServiceHandler.StopService)
	authGroup.POST("/apps/:id/redeploy", s.appServiceHandler.RedeployService)
	authGroup.POST("/apps/:id/restart", s.appServiceHandler.RestartService)
	authGroup.GET("/services/:serviceId/deployments", s.deploymentHandler.ListServiceDeployments)
	authGroup.POST("/services/:serviceId/deploy", s.deploymentHandler.Trigger)
	authGroup.POST("/deployments/:id/rollback", s.deploymentHandler.Rollback)
	authGroup.GET("/deployments/:id/logs", s.deploymentHandler.GetLogs, s.authGuard.RequireScope("logs:read"))
	authGroup.GET("/services/:serviceId/metrics", s.deploymentHandler.GetMetrics)
	authGroup.GET("/services/:serviceId/metrics/historical", s.metricsHandler.GetHistoricalMetrics)
	authGroup.GET("/services/:serviceId/logs/historical", s.logHandler.GetHistoricalLogs)
	authGroup.GET("/services/:serviceId/variables", s.serviceVarHandler.List)
	authGroup.POST("/services/:serviceId/variables", s.serviceVarHandler.Create)
	authGroup.PUT("/services/:serviceId/variables/:id", s.serviceVarHandler.Update)
	authGroup.DELETE("/services/:serviceId/variables/:id", s.serviceVarHandler.Delete)
	authGroup.GET("/audit-logs", s.auditLogHandler.List)
	authGroup.GET("/services/:serviceId/serverless/code", s.serverlessHandler.GetCode)
	authGroup.POST("/services/:serviceId/serverless/code", s.serverlessHandler.SaveCode)
	authGroup.GET("/projects/:projectId/webhooks", s.projectSettingsHandler.ListWebhooks)
	authGroup.POST("/projects/:projectId/webhooks", s.projectSettingsHandler.CreateWebhook)
	authGroup.DELETE("/projects/:projectId/webhooks/:id", s.projectSettingsHandler.DeleteWebhook)
	authGroup.GET("/projects/:projectId/tokens", s.projectSettingsHandler.ListTokens, s.authGuard.RequireScope("env:read"))
	authGroup.POST("/projects/:projectId/tokens", s.projectSettingsHandler.CreateToken, s.authGuard.RequireScope("env:write"))
	authGroup.DELETE("/projects/:projectId/tokens/:id", s.projectSettingsHandler.DeleteToken, s.authGuard.RequireScope("env:write"))
	authGroup.GET("/projects/:projectId/members", s.projectSettingsHandler.ListMembers)
	authGroup.POST("/projects/:projectId/members", s.projectSettingsHandler.AddMember)
	authGroup.DELETE("/projects/:projectId/members/:id", s.projectSettingsHandler.RemoveMember)
	authGroup.GET("/backups", s.backupHandler.List)
	authGroup.POST("/backups", s.backupHandler.Create)
	authGroup.GET("/backups/:id", s.backupHandler.Get)
	authGroup.DELETE("/backups/:id", s.backupHandler.Delete)
	authGroup.POST("/backups/:id/trigger", s.backupHandler.Trigger)
	authGroup.POST("/backups/:id/restore", s.backupHandler.Restore)
	authGroup.GET("/backups/:id/records", s.backupHandler.ListRecords)
	authGroup.GET("/backups/:id/records/:recordId/download", s.backupHandler.DownloadRecord)
	authGroup.DELETE("/backups/:id/records/:recordId", s.backupHandler.DeleteRecord)
	authGroup.GET("/s3-destinations", s.backupHandler.ListS3Destinations)
	authGroup.POST("/s3-destinations", s.backupHandler.CreateS3Destination)
	authGroup.DELETE("/s3-destinations/:id", s.backupHandler.DeleteS3Destination)
	authGroup.GET("/settings", s.settingsHandler.GetSettings)
	apiGroup.PUT("/settings", s.settingsHandler.UpdateSettings, s.authGuard.RequireRole("admin"))

	authGroup.GET("/ai", s.aiSettingsHandler.GetAISettings)
	apiGroup.PUT("/ai", s.aiSettingsHandler.UpdateAISettings, s.authGuard.RequireRole("admin"))

	authGroup.GET("/notifications", s.notifSettingsHandler.GetNotificationSettings)
	apiGroup.PUT("/notifications", s.notifSettingsHandler.UpdateNotificationSettings, s.authGuard.RequireRole("admin"))
	authGroup.GET("/settings/updates/status", s.updaterHandler.GetUpdateStatus)
	apiGroup.POST("/settings/updates/check", s.updaterHandler.CheckUpdate, s.authGuard.RequireRole("admin"))
	apiGroup.POST("/settings/updates/deploy", s.updaterHandler.DeployUpdate, s.authGuard.RequireRole("admin"))
	authGroup.GET("/mcp/sse", s.HandleMCPSSE)
	authGroup.POST("/mcp/messages", s.HandleMCPMessage)
	authGroup.GET("/profile", s.userHandler.GetProfile)
	authGroup.PUT("/profile", s.userHandler.UpdateProfile)
	authGroup.POST("/profile/email/request", s.userHandler.RequestEmailChange)
	authGroup.POST("/profile/email/verify", s.userHandler.VerifyEmailChange)
	authGroup.PUT("/profile/password", s.userHandler.ChangePassword)
	authGroup.GET("/profile/tokens", s.userHandler.ListPATs)
	authGroup.POST("/profile/tokens", s.userHandler.CreatePAT)
	authGroup.DELETE("/profile/tokens/:id", s.userHandler.DeletePAT)
	apiGroup.POST("/settings/notifications/test", s.notificationHandler.TestNotification, s.authGuard.RequireRole("admin"))
	authGroup.GET("/settings/oauth/providers", s.oauthHandler.ListProviders)
	apiGroup.PUT("/settings/oauth/providers", s.oauthHandler.SaveProvider, s.authGuard.RequireRole("admin"))
	apiGroup.GET("/auth/oauth/providers/enabled", s.oauthHandler.ListEnabledProviders)
	apiGroup.GET("/auth/oauth/:provider", s.oauthHandler.OAuthRedirect)
	apiGroup.GET("/auth/oauth/:provider/callback", s.oauthHandler.OAuthCallback)
	authGroup.POST("/auth/2fa/setup", s.oauthHandler.Setup2FA)
	authGroup.POST("/auth/2fa/verify", s.oauthHandler.Verify2FA)
	authGroup.POST("/auth/2fa/disable", s.oauthHandler.Disable2FA)
	apiGroup.GET("/ws/terminal/:id", s.terminalHandler.HandleWebSocket)

	apiGroup.POST("/settings/git_apps/github/manifest-callback", s.gitAppsHandler.ExchangeGithubManifestCode, s.authGuard.RequireRole("admin"))
	authGroup.GET("/settings/git_apps/github", s.gitAppsHandler.ListGithubApps)
	authGroup.GET("/settings/git_apps/github/:id", s.gitAppsHandler.GetGithubApp)
	apiGroup.PUT("/settings/git_apps/github", s.gitAppsHandler.SaveGithubApp, s.authGuard.RequireRole("admin"))
	apiGroup.DELETE("/settings/git_apps/github/:id", s.gitAppsHandler.DeleteGithubApp, s.authGuard.RequireRole("admin"))

	apiGroup.GET("/ws/services/:id/terminal", s.terminalHandler.HandleWebSocket)
	s.setupSPAFallback()
}

func (s *Server) setupSPAFallback() {
	staticDir := os.Getenv("VESSL_STATIC_DIR")

	if staticDir != "" {
		if stat, err := os.Stat(staticDir); err == nil && stat.IsDir() {
			s.router.GET("/*", func(c echo.Context) error {
				path := filepath.Join(staticDir, filepath.Clean(c.Request().URL.Path))
				if _, err := os.Stat(path); os.IsNotExist(err) {
					return c.File(filepath.Join(staticDir, "index.html"))
				}
				return c.File(path)
			})
			return
		}
	}

	dashboard.RegisterHandlers(s.router)
}
