#!/usr/bin/env bash
# Vessl 1-Click Installer
# Usage: curl -fsSL https://get.vessl.dev | sh
set -eo pipefail

RELEASE=${VESSL_VERSION:-latest}
VESSL_DIR=/vessl
REPO_URL="https://raw.githubusercontent.com/vesslhq/vessl/main"
COMPOSE_URL="$REPO_URL/docker-compose.yml"
CTL_URL="$REPO_URL/bootstrap/vesslctl"
BOLD="\033[1m"
DIM="\033[2m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
NC="\033[0m"

echo -e "${BOLD}🛰️  Vessl — Installing v${RELEASE}${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# --- Root check ---
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}❌ Please run as root (or with sudo).${NC}"
  exit 1
fi

# --- System checks ---
echo -e "${BOLD}🔍 System check${NC}"
TOTAL_RAM=$(free -m | awk '/^Mem:/{print $2}')
if [ "$TOTAL_RAM" -lt 1024 ]; then
  echo -e "  ${YELLOW}⚠️  ${TOTAL_RAM}MB RAM detected. 1GB+ recommended for Docker builds.${NC}"
  SWAP=$(free -m | awk '/^Swap:/{print $2}')
  if [ "$SWAP" -eq 0 ]; then
    echo -e "  ${YELLOW}   No swap configured. Docker builds may fail on low memory.${NC}"
    echo -e "  ${YELLOW}   Consider adding swap:${NC}"
    echo -e "  ${DIM}    fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile${NC}"
  else
    echo -e "  ${GREEN}✅ ${SWAP}MB swap detected.${NC}"
  fi
else
  echo -e "  ${GREEN}✅ ${TOTAL_RAM}MB RAM${NC}"
fi

# --- Port check ---
echo -e "${BOLD}🔌 Port check${NC}"
for PORT in 80 443 8080; do
  if ss -tlnp "sport = :$PORT" 2>/dev/null | grep -q .; then
    echo -e "  ${YELLOW}⚠️  Port $PORT is already in use. Vessl needs it.${NC}"
  else
    echo -e "  ${GREEN}✅ Port $PORT available${NC}"
  fi
done

# --- Detect server IP ---
SERVER_IP=$(curl -4fsS ifconfig.me 2>/dev/null || echo "your-server-ip")
echo -e "  ${GREEN}✅ Server IP: ${SERVER_IP}${NC}"

echo ""

# --- Docker ---
if ! command -v docker &> /dev/null; then
  echo -e "${BOLD}📦 Installing Docker...${NC}"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi

if ! docker info &> /dev/null; then
  echo -e "${YELLOW}⏳ Waiting for Docker...${NC}"
  sleep 3
fi

# Ensure Docker Compose plugin is available
if ! docker compose version &> /dev/null; then
  echo -e "${YELLOW}📦 Installing Docker Compose plugin...${NC}"
  apt-get update -qq && apt-get install -y -qq docker-compose-plugin 2>/dev/null || \
    echo -e "${YELLOW}⚠️  Could not install compose plugin. Run: apt-get install docker-compose-plugin${NC}"
fi

echo -e "${GREEN}✅ Docker ready${NC}"

# --- Directory setup ---
mkdir -p "$VESSL_DIR"/data/{backups,traefik,builds,storage}

# --- Pull files ---
echo -e "${BOLD}⬇️  Fetching configuration files...${NC}"
curl -fsSL "$COMPOSE_URL" -o "$VESSL_DIR/docker-compose.yml"
curl -fsSL "$CTL_URL" -o "$VESSL_DIR/vesslctl"
chmod +x "$VESSL_DIR/vesslctl"

# Install vesslctl to PATH
ln -sf "$VESSL_DIR/vesslctl" /usr/local/bin/vesslctl

# --- .env generation ---
if [ ! -f "$VESSL_DIR/.env" ]; then
  echo -e "${BOLD}🔑 Generating .env file...${NC}"

  JWT_SECRET=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)

  # Prompt for Let's Encrypt email
  TLS_EMAIL=""
  echo ""
  echo -e "📧 ${BOLD}Optional:${NC} Enter your email for automatic Let's Encrypt SSL."
  echo "   (Press Enter to skip — configure later via Settings or 'vesslctl config')"
  read -r -p "   Email: " TLS_EMAIL_INPUT </dev/tty
  if [ -n "$TLS_EMAIL_INPUT" ]; then
    TLS_EMAIL="$TLS_EMAIL_INPUT"
  fi

  cat > "$VESSL_DIR/.env" <<ENV
# Vessl Environment Configuration
# Auto-generated by installer. Edit if needed, then restart: docker compose restart

# Core
PORT=8080
HOST=0.0.0.0
VESSL_DATA_DIR=/vessl/data
VESSL_HOST_IP=

# Security (required - change this in production!)
VESSL_JWT_SECRET=${JWT_SECRET}

# Let's Encrypt SSL (for automatic HTTPS on custom domains)
# Leave empty if you don't have a domain or want to configure later
VESSL_TLS_EMAIL=${TLS_EMAIL}

# Docker
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Dashboard (required for notifications)
VESSL_DASHBOARD_URL=http://${SERVER_IP}:8080

# Docker Deployments
VESSL_RUNTIME_NETWORK=vessl-network
DEPLOY_HOST_PORT_START=4100
DEPLOY_HOST_PORT_END=4999
DEPLOY_DRY_RUN=false

# Updates (change to your fork if forked)
VESSL_UPDATE_URL=https://api.github.com/repos/vesslhq/vessl/releases/latest
VESSL_DOWNLOAD_URL=https://github.com/vesslhq/vessl/releases
ENV
fi

# --- Pull & start ---
echo -e "${BOLD}🐳 Pulling vessl:v${RELEASE}...${NC}"
docker compose -f "$VESSL_DIR/docker-compose.yml" pull
echo -e "${BOLD}🚀 Starting Vessl...${NC}"
docker compose -f "$VESSL_DIR/docker-compose.yml" up -d

# --- Health check ---
echo -e "${BOLD}⏳ Waiting for Vessl to become healthy...${NC}"
for i in $(seq 1 30); do
  if curl -sfS "http://localhost:8080/api/system/public" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Vessl is healthy and accepting requests.${NC}"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo -e "${YELLOW}⚠️  Vessl is starting but not yet responding. Run 'vesslctl logs -f' to check.${NC}"
  fi
  sleep 2
done

# --- systemd service (optional) ---
if command -v systemctl &> /dev/null; then
  cat > /etc/systemd/system/vessl.service <<'SERVICE'
[Unit]
Description=Vessl – Self-hosted PaaS
After=docker.service
Requires=docker.service

[Service]
Restart=always
RestartSec=10
WorkingDirectory=/vessl
ExecStartPre=-/usr/bin/docker compose -f /vessl/docker-compose.yml down
ExecStart=/usr/bin/docker compose -f /vessl/docker-compose.yml up
ExecStop=/usr/bin/docker compose -f /vessl/docker-compose.yml down

[Install]
WantedBy=multi-user.target
SERVICE
  systemctl daemon-reload
  systemctl enable --now vessl.service
fi

# --- Post-install summary ---
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅  Vessl v${RELEASE} installed successfully!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  ${BOLD}📍 Dashboard:${NC}  http://${SERVER_IP}:8080"
echo -e "  ${BOLD}📖 Docs:${NC}       https://docs.vessl.dev"
echo -e "  ${BOLD}🛠️  CLI:${NC}        vesslctl --help"
echo ""

if [ -n "$TLS_EMAIL" ]; then
  echo -e "  ${GREEN}🔒 SSL:       Enabled for ${TLS_EMAIL}${NC}"
else
  echo -e "  ${YELLOW}🔒 SSL:       Not configured${NC} (set up later in Settings or .env)"
fi

TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
echo -e "  ${DIM}📊 System:     ${TOTAL_RAM_MB}MB RAM, $(nproc) CPU cores${NC}"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "  1. Open the dashboard and create your admin account."
echo -e "  2. Or run: ${BOLD}vesslctl setup${NC} to create an admin from the terminal."
echo ""
echo -e "  ${DIM}Run 'vesslctl status' to check daemon health.${NC}"
echo -e "  ${DIM}Run 'vesslctl logs -f' to follow daemon logs.${NC}"
echo ""

# --- Offer to run setup ---
echo -e "📋 Would you like to create an admin account now? (y/N)"
read -r -p "   " RUN_SETUP </dev/tty
if [ "$RUN_SETUP" = "y" ] || [ "$RUN_SETUP" = "Y" ]; then
  echo ""
  vesslctl setup
  echo ""
  echo -e "${GREEN}✅ Admin account created. You can now log in at http://${SERVER_IP}:8080${NC}"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
