CREATE TABLE IF NOT EXISTS notification_settings (
    id TEXT PRIMARY KEY,
    discord_webhook_url TEXT,
    discord_ping_enabled BOOLEAN DEFAULT FALSE,
    discord_enabled BOOLEAN DEFAULT FALSE,
    slack_webhook_url TEXT,
    slack_enabled BOOLEAN DEFAULT FALSE,
    telegram_bot_token TEXT,
    telegram_chat_id TEXT,
    telegram_enabled BOOLEAN DEFAULT FALSE,
    smtp_host TEXT,
    smtp_port INTEGER DEFAULT 587,
    smtp_user TEXT,
    smtp_password TEXT,
    smtp_from_name TEXT,
    smtp_from_address TEXT,
    smtp_enabled BOOLEAN DEFAULT FALSE,
    resend_api_key TEXT,
    resend_enabled BOOLEAN DEFAULT FALSE,
    pushover_user_key TEXT,
    pushover_api_token TEXT,
    pushover_enabled BOOLEAN DEFAULT FALSE,
    generic_webhook_url TEXT,
    generic_webhook_enabled BOOLEAN DEFAULT FALSE,
    notification_alerts BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
