/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardMarketplaceRouteImport } from './routes/_dashboard.marketplace'
import { Route as DashboardDatabasesRouteImport } from './routes/_dashboard.databases'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSetupRouteImport } from './routes/_auth.setup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard.settings/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard.profile/index'
import { Route as DashboardSettingsUsersRouteImport } from './routes/_dashboard.settings/users'
import { Route as DashboardSettingsUpdatesRouteImport } from './routes/_dashboard.settings/updates'
import { Route as DashboardSettingsOauthRouteImport } from './routes/_dashboard.settings/oauth'
import { Route as DashboardSettingsMigrationRouteImport } from './routes/_dashboard.settings/migration'
import { Route as DashboardSettingsMaintenanceRouteImport } from './routes/_dashboard.settings/maintenance'
import { Route as DashboardSettingsGitAppsRouteImport } from './routes/_dashboard.settings/git-apps'
import { Route as DashboardSettingsDnsRouteImport } from './routes/_dashboard.settings/dns'
import { Route as DashboardSettingsBackupsRouteImport } from './routes/_dashboard.settings/backups'
import { Route as DashboardImportsVercelRouteImport } from './routes/_dashboard.imports/vercel'
import { Route as DashboardImportsRailwayRouteImport } from './routes/_dashboard.imports/railway'
import { Route as DashboardServicesServiceIdIndexRouteImport } from './routes/_dashboard.services/$serviceId.index'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard.projects/$projectId.index'
import { Route as DashboardDatabasesDbIdIndexRouteImport } from './routes/_dashboard.databases/$dbId.index'
import { Route as DashboardServicesServiceIdVariablesRouteImport } from './routes/_dashboard.services/$serviceId.variables'
import { Route as DashboardServicesServiceIdTerminalRouteImport } from './routes/_dashboard.services/$serviceId.terminal'
import { Route as DashboardServicesServiceIdServerlessRouteImport } from './routes/_dashboard.services/$serviceId.serverless'
import { Route as DashboardServicesServiceIdDomainsRouteImport } from './routes/_dashboard.services/$serviceId.domains'
import { Route as DashboardServicesServiceIdDeploymentsRouteImport } from './routes/_dashboard.services/$serviceId.deployments'
import { Route as DashboardServicesServiceIdBuildRouteImport } from './routes/_dashboard.services/$serviceId.build'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/_dashboard.projects/$projectId.settings'
import { Route as DashboardProjectsProjectIdJobsRouteImport } from './routes/_dashboard.projects/$projectId.jobs'
import { Route as DashboardProjectsProjectIdComposeRouteImport } from './routes/_dashboard.projects/$projectId.compose'
import { Route as DashboardProjectsProjectIdCanvasRouteImport } from './routes/_dashboard.projects/$projectId.canvas'
import { Route as DashboardDatabasesDbIdQueryRouteImport } from './routes/_dashboard.databases/$dbId.query'
import { Route as DashboardDatabasesDbIdDataRouteImport } from './routes/_dashboard.databases/$dbId.data'
import { Route as DashboardDatabasesDbIdBackupsRouteImport } from './routes/_dashboard.databases/$dbId.backups'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUsersRoute = DashboardSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUpdatesRoute =
  DashboardSettingsUpdatesRouteImport.update({
    id: '/settings/updates',
    path: '/settings/updates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsOauthRoute = DashboardSettingsOauthRouteImport.update({
  id: '/settings/oauth',
  path: '/settings/oauth',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsMigrationRoute =
  DashboardSettingsMigrationRouteImport.update({
    id: '/settings/migration',
    path: '/settings/migration',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsMaintenanceRoute =
  DashboardSettingsMaintenanceRouteImport.update({
    id: '/settings/maintenance',
    path: '/settings/maintenance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsGitAppsRoute =
  DashboardSettingsGitAppsRouteImport.update({
    id: '/settings/git-apps',
    path: '/settings/git-apps',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsDnsRoute = DashboardSettingsDnsRouteImport.update({
  id: '/settings/dns',
  path: '/settings/dns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsBackupsRoute =
  DashboardSettingsBackupsRouteImport.update({
    id: '/settings/backups',
    path: '/settings/backups',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardImportsVercelRoute = DashboardImportsVercelRouteImport.update({
  id: '/imports/vercel',
  path: '/imports/vercel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportsRailwayRoute = DashboardImportsRailwayRouteImport.update({
  id: '/imports/railway',
  path: '/imports/railway',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesServiceIdIndexRoute =
  DashboardServicesServiceIdIndexRouteImport.update({
    id: '/services/$serviceId/',
    path: '/services/$serviceId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardDatabasesDbIdIndexRoute =
  DashboardDatabasesDbIdIndexRouteImport.update({
    id: '/$dbId/',
    path: '/$dbId/',
    getParentRoute: () => DashboardDatabasesRoute,
  } as any)
const DashboardServicesServiceIdVariablesRoute =
  DashboardServicesServiceIdVariablesRouteImport.update({
    id: '/services/$serviceId/variables',
    path: '/services/$serviceId/variables',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdTerminalRoute =
  DashboardServicesServiceIdTerminalRouteImport.update({
    id: '/services/$serviceId/terminal',
    path: '/services/$serviceId/terminal',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdServerlessRoute =
  DashboardServicesServiceIdServerlessRouteImport.update({
    id: '/services/$serviceId/serverless',
    path: '/services/$serviceId/serverless',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdDomainsRoute =
  DashboardServicesServiceIdDomainsRouteImport.update({
    id: '/services/$serviceId/domains',
    path: '/services/$serviceId/domains',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdDeploymentsRoute =
  DashboardServicesServiceIdDeploymentsRouteImport.update({
    id: '/services/$serviceId/deployments',
    path: '/services/$serviceId/deployments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdBuildRoute =
  DashboardServicesServiceIdBuildRouteImport.update({
    id: '/services/$serviceId/build',
    path: '/services/$serviceId/build',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/$projectId/settings',
    path: '/$projectId/settings',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdJobsRoute =
  DashboardProjectsProjectIdJobsRouteImport.update({
    id: '/$projectId/jobs',
    path: '/$projectId/jobs',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdComposeRoute =
  DashboardProjectsProjectIdComposeRouteImport.update({
    id: '/$projectId/compose',
    path: '/$projectId/compose',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdCanvasRoute =
  DashboardProjectsProjectIdCanvasRouteImport.update({
    id: '/$projectId/canvas',
    path: '/$projectId/canvas',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardDatabasesDbIdQueryRoute =
  DashboardDatabasesDbIdQueryRouteImport.update({
    id: '/$dbId/query',
    path: '/$dbId/query',
    getParentRoute: () => DashboardDatabasesRoute,
  } as any)
const DashboardDatabasesDbIdDataRoute =
  DashboardDatabasesDbIdDataRouteImport.update({
    id: '/$dbId/data',
    path: '/$dbId/data',
    getParentRoute: () => DashboardDatabasesRoute,
  } as any)
const DashboardDatabasesDbIdBackupsRoute =
  DashboardDatabasesDbIdBackupsRouteImport.update({
    id: '/$dbId/backups',
    path: '/$dbId/backups',
    getParentRoute: () => DashboardDatabasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/databases': typeof DashboardDatabasesRouteWithChildren
  '/marketplace': typeof DashboardMarketplaceRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/imports/railway': typeof DashboardImportsRailwayRoute
  '/imports/vercel': typeof DashboardImportsVercelRoute
  '/settings/backups': typeof DashboardSettingsBackupsRoute
  '/settings/dns': typeof DashboardSettingsDnsRoute
  '/settings/git-apps': typeof DashboardSettingsGitAppsRoute
  '/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/settings/migration': typeof DashboardSettingsMigrationRoute
  '/settings/oauth': typeof DashboardSettingsOauthRoute
  '/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/profile/': typeof DashboardProfileIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/databases/$dbId/backups': typeof DashboardDatabasesDbIdBackupsRoute
  '/databases/$dbId/data': typeof DashboardDatabasesDbIdDataRoute
  '/databases/$dbId/query': typeof DashboardDatabasesDbIdQueryRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/databases/$dbId/': typeof DashboardDatabasesDbIdIndexRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/databases': typeof DashboardDatabasesRouteWithChildren
  '/marketplace': typeof DashboardMarketplaceRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/imports/railway': typeof DashboardImportsRailwayRoute
  '/imports/vercel': typeof DashboardImportsVercelRoute
  '/settings/backups': typeof DashboardSettingsBackupsRoute
  '/settings/dns': typeof DashboardSettingsDnsRoute
  '/settings/git-apps': typeof DashboardSettingsGitAppsRoute
  '/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/settings/migration': typeof DashboardSettingsMigrationRoute
  '/settings/oauth': typeof DashboardSettingsOauthRoute
  '/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/databases/$dbId/backups': typeof DashboardDatabasesDbIdBackupsRoute
  '/databases/$dbId/data': typeof DashboardDatabasesDbIdDataRoute
  '/databases/$dbId/query': typeof DashboardDatabasesDbIdQueryRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/databases/$dbId': typeof DashboardDatabasesDbIdIndexRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/databases': typeof DashboardDatabasesRouteWithChildren
  '/_dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/imports/railway': typeof DashboardImportsRailwayRoute
  '/_dashboard/imports/vercel': typeof DashboardImportsVercelRoute
  '/_dashboard/settings/backups': typeof DashboardSettingsBackupsRoute
  '/_dashboard/settings/dns': typeof DashboardSettingsDnsRoute
  '/_dashboard/settings/git-apps': typeof DashboardSettingsGitAppsRoute
  '/_dashboard/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/_dashboard/settings/migration': typeof DashboardSettingsMigrationRoute
  '/_dashboard/settings/oauth': typeof DashboardSettingsOauthRoute
  '/_dashboard/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/_dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/databases/$dbId/backups': typeof DashboardDatabasesDbIdBackupsRoute
  '/_dashboard/databases/$dbId/data': typeof DashboardDatabasesDbIdDataRoute
  '/_dashboard/databases/$dbId/query': typeof DashboardDatabasesDbIdQueryRoute
  '/_dashboard/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/_dashboard/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/_dashboard/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/_dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/_dashboard/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/_dashboard/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/_dashboard/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/_dashboard/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/_dashboard/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/_dashboard/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/_dashboard/databases/$dbId/': typeof DashboardDatabasesDbIdIndexRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/signin'
    | '/signup'
    | '/databases'
    | '/marketplace'
    | '/projects'
    | '/imports/railway'
    | '/imports/vercel'
    | '/settings/backups'
    | '/settings/dns'
    | '/settings/git-apps'
    | '/settings/maintenance'
    | '/settings/migration'
    | '/settings/oauth'
    | '/settings/updates'
    | '/settings/users'
    | '/profile/'
    | '/settings/'
    | '/databases/$dbId/backups'
    | '/databases/$dbId/data'
    | '/databases/$dbId/query'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/jobs'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/databases/$dbId/'
    | '/projects/$projectId/'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/signin'
    | '/signup'
    | '/databases'
    | '/marketplace'
    | '/projects'
    | '/imports/railway'
    | '/imports/vercel'
    | '/settings/backups'
    | '/settings/dns'
    | '/settings/git-apps'
    | '/settings/maintenance'
    | '/settings/migration'
    | '/settings/oauth'
    | '/settings/updates'
    | '/settings/users'
    | '/profile'
    | '/settings'
    | '/databases/$dbId/backups'
    | '/databases/$dbId/data'
    | '/databases/$dbId/query'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/jobs'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/databases/$dbId'
    | '/projects/$projectId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/setup'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_dashboard/databases'
    | '/_dashboard/marketplace'
    | '/_dashboard/projects'
    | '/_dashboard/'
    | '/_dashboard/imports/railway'
    | '/_dashboard/imports/vercel'
    | '/_dashboard/settings/backups'
    | '/_dashboard/settings/dns'
    | '/_dashboard/settings/git-apps'
    | '/_dashboard/settings/maintenance'
    | '/_dashboard/settings/migration'
    | '/_dashboard/settings/oauth'
    | '/_dashboard/settings/updates'
    | '/_dashboard/settings/users'
    | '/_dashboard/profile/'
    | '/_dashboard/settings/'
    | '/_dashboard/databases/$dbId/backups'
    | '/_dashboard/databases/$dbId/data'
    | '/_dashboard/databases/$dbId/query'
    | '/_dashboard/projects/$projectId/canvas'
    | '/_dashboard/projects/$projectId/compose'
    | '/_dashboard/projects/$projectId/jobs'
    | '/_dashboard/projects/$projectId/settings'
    | '/_dashboard/services/$serviceId/build'
    | '/_dashboard/services/$serviceId/deployments'
    | '/_dashboard/services/$serviceId/domains'
    | '/_dashboard/services/$serviceId/serverless'
    | '/_dashboard/services/$serviceId/terminal'
    | '/_dashboard/services/$serviceId/variables'
    | '/_dashboard/databases/$dbId/'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/marketplace': {
      id: '/_dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/databases': {
      id: '/_dashboard/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/users': {
      id: '/_dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/updates': {
      id: '/_dashboard/settings/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof DashboardSettingsUpdatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/oauth': {
      id: '/_dashboard/settings/oauth'
      path: '/settings/oauth'
      fullPath: '/settings/oauth'
      preLoaderRoute: typeof DashboardSettingsOauthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/migration': {
      id: '/_dashboard/settings/migration'
      path: '/settings/migration'
      fullPath: '/settings/migration'
      preLoaderRoute: typeof DashboardSettingsMigrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/maintenance': {
      id: '/_dashboard/settings/maintenance'
      path: '/settings/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof DashboardSettingsMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/git-apps': {
      id: '/_dashboard/settings/git-apps'
      path: '/settings/git-apps'
      fullPath: '/settings/git-apps'
      preLoaderRoute: typeof DashboardSettingsGitAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/dns': {
      id: '/_dashboard/settings/dns'
      path: '/settings/dns'
      fullPath: '/settings/dns'
      preLoaderRoute: typeof DashboardSettingsDnsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/backups': {
      id: '/_dashboard/settings/backups'
      path: '/settings/backups'
      fullPath: '/settings/backups'
      preLoaderRoute: typeof DashboardSettingsBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/imports/vercel': {
      id: '/_dashboard/imports/vercel'
      path: '/imports/vercel'
      fullPath: '/imports/vercel'
      preLoaderRoute: typeof DashboardImportsVercelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/imports/railway': {
      id: '/_dashboard/imports/railway'
      path: '/imports/railway'
      fullPath: '/imports/railway'
      preLoaderRoute: typeof DashboardImportsRailwayRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/': {
      id: '/_dashboard/services/$serviceId/'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof DashboardServicesServiceIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/databases/$dbId/': {
      id: '/_dashboard/databases/$dbId/'
      path: '/$dbId'
      fullPath: '/databases/$dbId/'
      preLoaderRoute: typeof DashboardDatabasesDbIdIndexRouteImport
      parentRoute: typeof DashboardDatabasesRoute
    }
    '/_dashboard/services/$serviceId/variables': {
      id: '/_dashboard/services/$serviceId/variables'
      path: '/services/$serviceId/variables'
      fullPath: '/services/$serviceId/variables'
      preLoaderRoute: typeof DashboardServicesServiceIdVariablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/terminal': {
      id: '/_dashboard/services/$serviceId/terminal'
      path: '/services/$serviceId/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof DashboardServicesServiceIdTerminalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/serverless': {
      id: '/_dashboard/services/$serviceId/serverless'
      path: '/services/$serviceId/serverless'
      fullPath: '/services/$serviceId/serverless'
      preLoaderRoute: typeof DashboardServicesServiceIdServerlessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/domains': {
      id: '/_dashboard/services/$serviceId/domains'
      path: '/services/$serviceId/domains'
      fullPath: '/services/$serviceId/domains'
      preLoaderRoute: typeof DashboardServicesServiceIdDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/deployments': {
      id: '/_dashboard/services/$serviceId/deployments'
      path: '/services/$serviceId/deployments'
      fullPath: '/services/$serviceId/deployments'
      preLoaderRoute: typeof DashboardServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/build': {
      id: '/_dashboard/services/$serviceId/build'
      path: '/services/$serviceId/build'
      fullPath: '/services/$serviceId/build'
      preLoaderRoute: typeof DashboardServicesServiceIdBuildRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId/settings': {
      id: '/_dashboard/projects/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/jobs': {
      id: '/_dashboard/projects/$projectId/jobs'
      path: '/$projectId/jobs'
      fullPath: '/projects/$projectId/jobs'
      preLoaderRoute: typeof DashboardProjectsProjectIdJobsRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/compose': {
      id: '/_dashboard/projects/$projectId/compose'
      path: '/$projectId/compose'
      fullPath: '/projects/$projectId/compose'
      preLoaderRoute: typeof DashboardProjectsProjectIdComposeRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/canvas': {
      id: '/_dashboard/projects/$projectId/canvas'
      path: '/$projectId/canvas'
      fullPath: '/projects/$projectId/canvas'
      preLoaderRoute: typeof DashboardProjectsProjectIdCanvasRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/databases/$dbId/query': {
      id: '/_dashboard/databases/$dbId/query'
      path: '/$dbId/query'
      fullPath: '/databases/$dbId/query'
      preLoaderRoute: typeof DashboardDatabasesDbIdQueryRouteImport
      parentRoute: typeof DashboardDatabasesRoute
    }
    '/_dashboard/databases/$dbId/data': {
      id: '/_dashboard/databases/$dbId/data'
      path: '/$dbId/data'
      fullPath: '/databases/$dbId/data'
      preLoaderRoute: typeof DashboardDatabasesDbIdDataRouteImport
      parentRoute: typeof DashboardDatabasesRoute
    }
    '/_dashboard/databases/$dbId/backups': {
      id: '/_dashboard/databases/$dbId/backups'
      path: '/$dbId/backups'
      fullPath: '/databases/$dbId/backups'
      preLoaderRoute: typeof DashboardDatabasesDbIdBackupsRouteImport
      parentRoute: typeof DashboardDatabasesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardDatabasesRouteChildren {
  DashboardDatabasesDbIdBackupsRoute: typeof DashboardDatabasesDbIdBackupsRoute
  DashboardDatabasesDbIdDataRoute: typeof DashboardDatabasesDbIdDataRoute
  DashboardDatabasesDbIdQueryRoute: typeof DashboardDatabasesDbIdQueryRoute
  DashboardDatabasesDbIdIndexRoute: typeof DashboardDatabasesDbIdIndexRoute
}

const DashboardDatabasesRouteChildren: DashboardDatabasesRouteChildren = {
  DashboardDatabasesDbIdBackupsRoute: DashboardDatabasesDbIdBackupsRoute,
  DashboardDatabasesDbIdDataRoute: DashboardDatabasesDbIdDataRoute,
  DashboardDatabasesDbIdQueryRoute: DashboardDatabasesDbIdQueryRoute,
  DashboardDatabasesDbIdIndexRoute: DashboardDatabasesDbIdIndexRoute,
}

const DashboardDatabasesRouteWithChildren =
  DashboardDatabasesRoute._addFileChildren(DashboardDatabasesRouteChildren)

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdCanvasRoute: typeof DashboardProjectsProjectIdCanvasRoute
  DashboardProjectsProjectIdComposeRoute: typeof DashboardProjectsProjectIdComposeRoute
  DashboardProjectsProjectIdJobsRoute: typeof DashboardProjectsProjectIdJobsRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdCanvasRoute: DashboardProjectsProjectIdCanvasRoute,
  DashboardProjectsProjectIdComposeRoute:
    DashboardProjectsProjectIdComposeRoute,
  DashboardProjectsProjectIdJobsRoute: DashboardProjectsProjectIdJobsRoute,
  DashboardProjectsProjectIdSettingsRoute:
    DashboardProjectsProjectIdSettingsRoute,
  DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardDatabasesRoute: typeof DashboardDatabasesRouteWithChildren
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardImportsRailwayRoute: typeof DashboardImportsRailwayRoute
  DashboardImportsVercelRoute: typeof DashboardImportsVercelRoute
  DashboardSettingsBackupsRoute: typeof DashboardSettingsBackupsRoute
  DashboardSettingsDnsRoute: typeof DashboardSettingsDnsRoute
  DashboardSettingsGitAppsRoute: typeof DashboardSettingsGitAppsRoute
  DashboardSettingsMaintenanceRoute: typeof DashboardSettingsMaintenanceRoute
  DashboardSettingsMigrationRoute: typeof DashboardSettingsMigrationRoute
  DashboardSettingsOauthRoute: typeof DashboardSettingsOauthRoute
  DashboardSettingsUpdatesRoute: typeof DashboardSettingsUpdatesRoute
  DashboardSettingsUsersRoute: typeof DashboardSettingsUsersRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardServicesServiceIdBuildRoute: typeof DashboardServicesServiceIdBuildRoute
  DashboardServicesServiceIdDeploymentsRoute: typeof DashboardServicesServiceIdDeploymentsRoute
  DashboardServicesServiceIdDomainsRoute: typeof DashboardServicesServiceIdDomainsRoute
  DashboardServicesServiceIdServerlessRoute: typeof DashboardServicesServiceIdServerlessRoute
  DashboardServicesServiceIdTerminalRoute: typeof DashboardServicesServiceIdTerminalRoute
  DashboardServicesServiceIdVariablesRoute: typeof DashboardServicesServiceIdVariablesRoute
  DashboardServicesServiceIdIndexRoute: typeof DashboardServicesServiceIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDatabasesRoute: DashboardDatabasesRouteWithChildren,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardImportsRailwayRoute: DashboardImportsRailwayRoute,
  DashboardImportsVercelRoute: DashboardImportsVercelRoute,
  DashboardSettingsBackupsRoute: DashboardSettingsBackupsRoute,
  DashboardSettingsDnsRoute: DashboardSettingsDnsRoute,
  DashboardSettingsGitAppsRoute: DashboardSettingsGitAppsRoute,
  DashboardSettingsMaintenanceRoute: DashboardSettingsMaintenanceRoute,
  DashboardSettingsMigrationRoute: DashboardSettingsMigrationRoute,
  DashboardSettingsOauthRoute: DashboardSettingsOauthRoute,
  DashboardSettingsUpdatesRoute: DashboardSettingsUpdatesRoute,
  DashboardSettingsUsersRoute: DashboardSettingsUsersRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardServicesServiceIdBuildRoute: DashboardServicesServiceIdBuildRoute,
  DashboardServicesServiceIdDeploymentsRoute:
    DashboardServicesServiceIdDeploymentsRoute,
  DashboardServicesServiceIdDomainsRoute:
    DashboardServicesServiceIdDomainsRoute,
  DashboardServicesServiceIdServerlessRoute:
    DashboardServicesServiceIdServerlessRoute,
  DashboardServicesServiceIdTerminalRoute:
    DashboardServicesServiceIdTerminalRoute,
  DashboardServicesServiceIdVariablesRoute:
    DashboardServicesServiceIdVariablesRoute,
  DashboardServicesServiceIdIndexRoute: DashboardServicesServiceIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
