version: "3.8"
services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    x-vessel:
      is_database: true
      connection_string: "redis://:${db.password}@${host}:${port}/0"
      backup:
        command: ["redis-cli", "SAVE"]
        file_extension: ".rdb"
    command:
      - dragonfly
      - --requirepass
      - ${db.password}
    volumes:
      - dragonfly-data:/data
