version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    x-vessel:
      is_database: true
      connection_string: "postgresql://${db.username}:${db.password}@${host}:${port}/${db.database_name}"
      backup:
        command: ["pg_dump", "-U", "${db.username}", "${db.database_name}"]
        file_extension: ".sql"
    environment:
      - POSTGRES_USER=${db.username}
      - POSTGRES_PASSWORD=${db.password}
      - POSTGRES_DB=${db.database_name}
    volumes:
      - pg-data:/var/lib/postgresql/data
