x-codedock:
  is_one_click: true
  name: Ghost
  description: Professional publishing platform
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2368"
    environment:
      - NODE_ENV=production
