x-codedock:
  is_one_click: true
  name: MinIO
  description: S3-compatible object storage
services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000"
    command:
      - server
      - /data
      - --console-address
      - ":9001"
