version: "3.8"
services:
  mongodb:
    image: mongo:7.0
    x-codedock:
      is_database: true
      connection_string: "mongodb://${db.username}:${db.password}@${host}:${port}/${db.database_name}?authSource=admin"
      backup:
        command: ["mongodump", "--archive"]
        file_extension: ".archive"
      restore:
        command: ["mongorestore", "--archive"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${db.username}
      - MONGO_INITDB_ROOT_PASSWORD=${db.password}
      - MONGO_INITDB_DATABASE=${db.database_name}
    volumes:
      - mongo-data:/data/db
