version: "3.8"
services:
  mysql:
    image: mysql:8.0
    x-vessl:
      is_database: true
      connection_string: "mysql://${db.username}:${db.password}@${host}:${port}/${db.database_name}"
      backup:
        command:
          ["mysqldump", "-u", "root", "-p${db.password}", "${db.database_name}"]
        file_extension: ".sql"
      restore:
        command:
          ["mysql", "-u", "root", "-p${db.password}", "${db.database_name}"]
    environment:
      - MYSQL_ROOT_PASSWORD=${db.password}
      - MYSQL_USER=${db.username}
      - MYSQL_PASSWORD=${db.password}
      - MYSQL_DATABASE=${db.database_name}
    volumes:
      - mysql-data:/var/lib/mysql
