version: "3.8"
services:
  nats:
    image: nats:2-alpine
    x-codedock:
      is_database: true
      connection_string: "nats://${host}:${port}"
    ports:
      - "4222:4222"
    command:
      - nats
      - --port
      - "${port}"
