x-codedock:
  is_one_click: true
  name: Plausible
  description: Privacy-friendly web analytics
services:
  plausible:
    image: plausible/analytics
    restart: always
    ports:
      - "8000"
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=plausible
