version: "3.8"
services:
  redis:
    image: redis:7-alpine
    x-codedock:
      is_database: true
      connection_string: "redis://:${db.password}@${host}:${port}/0"
      backup:
        command: ["redis-cli", "SAVE"]
        file_extension: ".rdb"
    command:
      - redis-server
      - --requirepass
      - ${db.password}
    volumes:
      - redis-data:/data
