version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    x-codedock:
      is_database: true
      connection_string: "postgresql://${db.username}:${db.password}@${host}:${port}/${db.database_name}"
      backup:
        command: ["pg_dump", "-U", "${db.username}", "${db.database_name}"]
        file_extension: ".sql"
      restore:
        command: ["psql", "-U", "${db.username}", "-d", "${db.database_name}"]
    environment:
      - POSTGRES_USER=${db.username}
      - POSTGRES_PASSWORD=${db.password}
      - POSTGRES_DB=${db.database_name}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
